name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.17
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FinalTECH Artifact
        path: build/libs/*.jar
